### ISSUE TITLE
Hosted Multiuser / Stripe Payments

### ISSUE THREAD

**Issue by hozza** [stringer-rss/stringer#1052]
Hey @mockdeep 

I spotted the ground works for Stripe payment subscriptions and multi-users. Is there a plan to offer a hosted version as well as keeping stringer self-hostable?

**Comment by mockdeep** [comment]
@hozza yeah, [it was/is my plan](https://github.com/stringer-rss/stringer/discussions/938) to integrate payments to offer a hosted version. I got taken up with other things, but I've got a working implementation on a branch that I'll eventually get back to. Is hosting something you'd be interested in? I also intend to keep it open and self-hostable, of course.

**Comment by hozza** [comment]
Good to know, it sounds like you're coming from the right place, I don't don't want to loose a great FOSS project to paid subs only! 

I may be interested in the hosted version too, depending on data collection. I have some experience with Stripe, feel free to tag me if you have any issues setting it up. :)

**Comment by mockdeep** [comment]
@hozza yeah, I have no intention of ever closing it off. I'm curious what you're thinking in terms of data collection. I would never do anything like selling data to advertisers or other third parties. On the off chance a lot of people start using it, I might want to build some custom analytics, but I'd probably roll that myself rather than pulling in a 3rd party tool.

If you were going to pay for hosting, do you have a sense of how much you'd be willing to pay for something like Stringer?
