### ISSUE TITLE
Filter feeds with jquery

### ISSUE THREAD

**Issue by warmwaffles** [stringer-rss/stringer#28]
I don't have a link off hand, but something similar to how heroku allows you to quickly filter your apps but with javascript that fuzzy searches the titles of all the stories.

**Comment by vanhalt** [comment]
For the record, just if somebody is interested in it. I implemented a basic [search/filter](https://github.com/vanhalt/stringer/commit/530822fbb0a6802769dd3ffd3a32fdc6327f0d7c) page using PG Full Text Search. It is not a big deal because I was in a rush and needed to filter a 1000 items feed so... that happened.

Hope that I can improve it later!
